### ISSUE TITLE
Chyba zobrazení počtu záznamů v tabulce

### ISSUE THREAD

**Issue by motyc** [petrpajdla/map_oao#6]
Showing **106 to 101** of 101 entries

![image](https://user-images.githubusercontent.com/20186892/166654291-af1ce542-8a59-41e8-97e5-d4e980c3e769.png)

**Comment by petrpajdla** [comment]
Díky, taky jsem si všiml, ale pak jsem tomu už nevěnoval pozornost. Mohlo by to nějak souviset se zalamováním řádků uvnitř položek, ale fakt nevím. 
Asi to úplně odstraním, je to nějaká vlastnost toho prvku tabulky a stejně to nejde přeložit a přidám nějakou základní statistiku zvlášť.

**Comment by petrpajdla** [comment]
![Screenshot_2022-05-04_12-55-09](https://user-images.githubusercontent.com/27239643/166668498-0962c8f8-c617-40ec-80e0-4bd18d293dc4.png)
