### ISSUE TITLE
Chyba v menu

### ISSUE THREAD

**Issue by motyc** [petrpajdla/map_oao#7]
1. Přejdu na https://oao.aiscr.cz/#!/about
2. Následně kliknu na nadpis
![image](https://user-images.githubusercontent.com/20186892/166654579-7d416b6d-1aec-4986-b1af-fa8b0f55c08e.png)
3. Změní se URL na https://oao.aiscr.cz/#!/, ale okno zůstane stejné (about).
4. Poté kliknu na Hledej podle polohy. 
![image](https://user-images.githubusercontent.com/20186892/166654726-feb88b45-46e3-4075-bea8-f37e4de46d1f.png)
5. URL zůstane https://oao.aiscr.cz/#!/ a mapa se neotevře (když předtím nekliknu na nadpis, funguje to normálně).

**Comment by petrpajdla** [comment]
Relikt posledních úprav kdy jsem se tam do více řádků snažil nacpat i popisek "Organizace s oprávněním..."

@motyc myslíš, že to nechat jako odkaz, který přejde na stránku "Hledej podle polohy" nebo jako prostý text?

**Comment by motyc** [comment]
Klidně ať to přechází na tu mapu, ale je to asi jedno... Obojí v pohodě.
