### ISSUE TITLE
Prohodit položky v menu?

### ISSUE THREAD

**Issue by motyc** [petrpajdla/map_oao#8]
Uvážil bych prohození položek "o aplikaci" a "Oznámit stavební záměr", nebo nějaké grafické odlišení/odsazení toho odkazu na oznámení...

**Comment by petrpajdla** [comment]
Zkoušel jsem odsadit aby to bylo jakoby zarovnané vpravo, ale vypadalo to divně. 
Prohodím s about.

**Comment by petrpajdla** [comment]
![map-oao-issue1](https://user-images.githubusercontent.com/27239643/166658158-283d59d3-e688-4ca1-ab8f-120b40053781.png)
